export interface IconSet {
  id: string
  label: string
  count: number
  icons: string[]
}

export const notificationIconSets: IconSet[] = [
  {
    id: "lucide",
    label: "Стандартный набор",
    count: 12,
    icons: [
      "Home",
      "MessageCircle",
      "Navigation",
      "Hand",
      "PhoneCall",
      "Bell",
      "Coffee",
      "ShoppingCart",
      "CloudRain",
      "Calendar",
      "BatteryCharging",
      "Gift",
    ],
  },
  {
    id: "material",
    label: "Материальная иконка",
    count: 12,
    icons: [
      "HomePlus",
      "MessageSquare",
      "MapPin",
      "PersonStanding",
      "PhoneOutgoing",
      "Home",
      "Coffee",
      "ShoppingCart",
      "CloudUpload",
      "UserPlus",
      "Battery",
      "Gift",
    ],
  },
  {
    id: "lucida",
    label: "Иконки Люцида",
    count: 12,
    icons: [
      "Home",
      "Send",
      "MapPin",
      "Handshake",
      "PhoneIncoming",
      "Bell",
      "Coffee",
      "ShoppingBag",
      "CloudRain",
      "Calendar",
      "Timer",
      "Gift",
    ],
  },
  {
    id: "phosphor",
    label: "Значок фосфора",
    count: 12,
    icons: [
      "Home",
      "MessageCircle",
      "Flag",
      "Hand",
      "PhoneCall",
      "Bell",
      "Coffee",
      "ShoppingBasket",
      "CloudRain",
      "CalendarCheck",
      "BatteryFull",
      "Box",
    ],
  },
  {
    id: "remix",
    label: "Remix Icon",
    count: 12,
    icons: [
      "Home",
      "MessageSquarePlus",
      "Navigation2",
      "Sparkles",
      "PhoneCall",
      "Bell",
      "Coffee",
      "ShoppingBag",
      "CloudRain",
      "CalendarDays",
      "BatteryCharging",
      "Package",
    ],
  },
]
