INSERT INTO builds (user_id, site_url, app_name, package_name, splash_color, theme_color, push_enabled, offline_enabled, push_provider, notification_icon_set, notification_icon_name, addon_ids, config, status)
VALUES (1, 'https://xn----utbhbbdxh.xn--p1ai/', 'Полутон Debug', 'com.poluton.debug', '#1A1025', '#ef4444', false, true, 'firebase', 'lucide', 'Bell', '[]'::jsonb, '{
  "appName": "Полутон Debug",
  "iconUrl": "https://cdn.poehali.dev/projects/b471473c-c1c9-4346-909f-afc6a80feb03/bucket/builder/icons/bf387798-30d8-40af-a900-8af62ce8b113.png",
  "siteUrl": "https://xn----utbhbbdxh.xn--p1ai/",
  "webAuth": true,
  "jsBridge": true,
  "allowHttp": false,
  "deepLinks": false,
  "kioskMode": false,
  "permMedia": true,
  "pinchZoom": false,
  "fullscreen": true,
  "permCamera": true,
  "splashType": "animation",
  "themeColor": "#ef4444",
  "navBarColor": "#FFFFFF",
  "orientation": "portrait",
  "packageName": "com.poluton.debug",
  "pushEnabled": false,
  "splashColor": "#1A1025",
  "versionCode": "1",
  "versionName": "1.0-debug",
  "disableCache": false,
  "permLocation": true,
  "pushProvider": "firebase",
  "permVibration": true,
  "appLockEnabled": false,
  "offlineEnabled": true,
  "permMicrophone": true,
  "splashBehavior": "once",
  "splashGradient": false,
  "statusBarColor": "#FFFFFF",
  "screenshotDisabled": false,
  "notificationIconSet": "lucide",
  "notificationIconName": "Bell",
  "customJs": "(function(){ try { var origGUM = navigator.mediaDevices.getUserMedia.bind(navigator.mediaDevices); navigator.mediaDevices.getUserMedia = function(c){ return origGUM(c).catch(function(err){ alert(\"MEDIA ERROR: \" + err.name + \" | \" + err.message); throw err; }); }; } catch(e) { alert(\"INIT ERROR: \" + e.message); } window.addEventListener(\"error\", function(e){ alert(\"JS ERROR: \" + e.message); }); window.addEventListener(\"unhandledrejection\", function(e){ alert(\"PROMISE ERROR: \" + (e.reason && e.reason.message ? e.reason.message : e.reason)); }); alert(\"DEBUG SCRIPT LOADED OK\"); })();"
}'::jsonb, 'building')
RETURNING id;